image: Ubuntu2204

stack: node 20

branches:
  only:
    - master

cache: node_modules

install:
  - yarn

build: off

build_script:
  - yarn run prod

test_script:
  - yarn run lint

deploy_script:
  - git config --global credential.helper store
  - git config --global user.name Gamurai
  - git config --global user.email g@murai.com
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - npx gh-pages -d dist -u "gamurai-bot <g@murai.com>"